[build]
command = "yarn build"
publish = "out"

[[plugins]]
package = "@netlify/plugin-nextjs"

[[plugins]]
package = "netlify-plugin-image-optim"

[[plugins]]
package = "@netlify/plugin-sitemap"

    [plugins.inputs]
    buildDir = "out"

